### PR TITLE
Add netstandard1_0, net20, net35 support

### PR DESCRIPTION
**Pull request by LonghronShen**
Add netstandard1_0, net20, net35 support.

* .NET Standard 1.0 (netstandard1.0)
* .NET Framework 2.0 (net20)
* .NET Framework 3.5 (net35)
* .NET Framework 4.5, Windows Runtime 8.0, Windows Phone 8.1 For Silverlight (Profile111, aka portable-net45+win8+wpa81)
* .NET Framework 4.03, Silverlight 5.0, Windows Runtime 8.0, Windows Phone 8.1 For Silverlight, Windows Phone 8 Runtime (Profile336, aka portable-net403+sl5+win8+wpa81+wp8)

### CODE REVIEW

**Comment by StefH** [comment]
Can you also fix the CodeFactor issues?

**Comment by LonghronShen** [comment]
I'm working on this~
Thank you for attention to this PR.

**Comment by LonghronShen** [comment]
Now issues have been all fixed.

**Comment by StefH** [comment]
Thanks.
I merged the code, if all is correct, I can create new NuGet ?

**Comment by LonghronShen** [comment]
Sure, I'm waiting for a new official NuGet package!

**Pull request merged**
